### ISSUE TITLE
Code review 1

### ISSUE THREAD

**Issue by ruokokoski** [mikaelri/Budgeting-Application-Project#1]
Notes:
* README-file provides a good overview of the project's status
* The application can be launched as described in the documentation
* The basic functionality of the app has been implemented (registering, login, creating new budgets)
* The code is easy to follow and has been divided into logical smaller files
* The application has still quite a lot to be done before it fulfills it's final purpose  

Some bugs I detected:
* Many users with same credentials can be created and stored in the database if using exactly the same username and the password in the registration form
* It is possible to create budgets with identical names. This should be prevented.

The database table 'budgets' have fields for expenses and income where initial values are stored when creating a new budget. 'Transactions'-table have the same fields. Maybe this is what you are already planning to do, but I would move all expenses and income from budgets to transactions because otherwise manipulating those numbers becomes a headache.

**Comment by mikaelri** [comment]
Thank you for the comments! Bugs you mentioned are a good points and actually were something under progress / noticed that were missing.

There is still work in progress with the budgets and transaction tables, but this was a good comment.

Thanks!
