### ISSUE TITLE
Code review #2

### ISSUE THREAD

**Issue by veetihytonen** [mikaelri/Budgeting-Application-Project#2]
Notes:
* README is written well and provides a comprehensive overview of the app
* Installing and running the app worked with no issues
* App fulfills course requirements in terms of functionality, security etc.
* App is close to feature complete
* Code quality is good, codebase is easy to read and is sensibly modularized

Bugs:
* I had an issue with doing anything at first, as while creating a new user, I got the error "KeyError: 'csrf_token' " in python when the "check_csrf()" function is used. It seems the session or the form (probably the session) isn't being given the CSRF attribute, which results in the key error. I avoided the issue by commenting out the lines where check_csrf() is used, but this should be easy to fix.
* In the Admin panel, only one budget per user is shown, and a user can be shown with a budget belonging to another user

Criticism:
* It would make for a more pleasant user experience if more redirects were used, eg. when a new user is created, the page would redirect to login page

Good job overall, the app just needs the finishing touches now!

**Comment by mikaelri** [comment]
Thank you for the comments!

I did not recognize first the csrf-issue as I had database put up for test and admin users, but noticed now (after this comment) and when clearing all the data and starting again testing the app. Made the changes for this so the registeration works now.

Good comment on the admin panel, I will think about the way to tackle this. Also will consider possible changes on the redirects for some of the functions.

Thanks!

**Comment by mikaelri** [comment]
Thank you for the comments!

I did not recognize first the csrf-issue as I had database put up for test and admin users, but noticed now (after this comment) and when clearing all the data and starting again testing the app. Made the changes for this so the registeration works now.

Good comment on the admin panel, I will think about the way to tackle this. Also will consider possible changes on the redirects for some of the functions.

Thanks!
